import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideBar from "../../../components/admin-panel/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const links = [
    { text: "General", url: "/admin/general" },
    { text: "Stats", url: "/admin/stats" },
  ];

  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <main className="grid grid-cols-[1fr_4fr] min-h-screen">
          <SideBar links={links} />
          <div>
            <div>Hello, admin!</div>
            <div>{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
